const authentication = require('./authentication');
const ArchiveApi = require('./Apis/ArchiveApi');
const CashbookApi = require('./Apis/CashbookApi');
const ClientsApi = require('./Apis/ClientsApi');
const CompaniesApi = require('./Apis/CompaniesApi');
const EmailsApi = require('./Apis/EmailsApi');
const InfoApi = require('./Apis/InfoApi');
const IssuedDocumentsApi = require('./Apis/IssuedDocumentsApi');
const IssuedEInvoicesApi = require('./Apis/IssuedEInvoicesApi');
const ProductsApi = require('./Apis/ProductsApi');
const ReceiptsApi = require('./Apis/ReceiptsApi');
const ReceivedDocumentsApi = require('./Apis/ReceivedDocumentsApi');
const SettingsApi = require('./Apis/SettingsApi');
const SuppliersApi = require('./Apis/SuppliersApi');
const TaxesApi = require('./Apis/TaxesApi');
const UserApi = require('./Apis/UserApi');
const WebhooksApi = require('./Apis/WebhooksApi');

module.exports = {
    version: require('./package.json').version,
    platformVersion: require('zapier-platform-core').version,
    authentication: authentication,
    creates: {
        [ArchiveApi.createArchiveDocument.key]: ArchiveApi.createArchiveDocument,
        [ArchiveApi.deleteArchiveDocument.key]: ArchiveApi.deleteArchiveDocument,
        [ArchiveApi.getArchiveDocument.key]: ArchiveApi.getArchiveDocument,
        [ArchiveApi.listArchiveDocuments.key]: ArchiveApi.listArchiveDocuments,
        [ArchiveApi.modifyArchiveDocument.key]: ArchiveApi.modifyArchiveDocument,
        [ArchiveApi.uploadArchiveDocumentAttachment.key]: ArchiveApi.uploadArchiveDocumentAttachment,
        [CashbookApi.createCashbookEntry.key]: CashbookApi.createCashbookEntry,
        [CashbookApi.deleteCashbookEntry.key]: CashbookApi.deleteCashbookEntry,
        [CashbookApi.getCashbookEntry.key]: CashbookApi.getCashbookEntry,
        [CashbookApi.listCashbookEntries.key]: CashbookApi.listCashbookEntries,
        [CashbookApi.modifyCashbookEntry.key]: CashbookApi.modifyCashbookEntry,
        [ClientsApi.createClient.key]: ClientsApi.createClient,
        [ClientsApi.deleteClient.key]: ClientsApi.deleteClient,
        [ClientsApi.getClient.key]: ClientsApi.getClient,
        [ClientsApi.listClients.key]: ClientsApi.listClients,
        [ClientsApi.modifyClient.key]: ClientsApi.modifyClient,
        [CompaniesApi.getCompanyInfo.key]: CompaniesApi.getCompanyInfo,
        [EmailsApi.listEmails.key]: EmailsApi.listEmails,
        [InfoApi.listArchiveCategories.key]: InfoApi.listArchiveCategories,
        [InfoApi.listCities.key]: InfoApi.listCities,
        [InfoApi.listCostCenters.key]: InfoApi.listCostCenters,
        [InfoApi.listCountries.key]: InfoApi.listCountries,
        [InfoApi.listCurrencies.key]: InfoApi.listCurrencies,
        [InfoApi.listDeliveryNotesDefaultCausals.key]: InfoApi.listDeliveryNotesDefaultCausals,
        [InfoApi.listDetailedCountries.key]: InfoApi.listDetailedCountries,
        [InfoApi.listLanguages.key]: InfoApi.listLanguages,
        [InfoApi.listPaymentAccounts.key]: InfoApi.listPaymentAccounts,
        [InfoApi.listPaymentMethods.key]: InfoApi.listPaymentMethods,
        [InfoApi.listProductCategories.key]: InfoApi.listProductCategories,
        [InfoApi.listReceivedDocumentCategories.key]: InfoApi.listReceivedDocumentCategories,
        [InfoApi.listRevenueCenters.key]: InfoApi.listRevenueCenters,
        [InfoApi.listTemplates.key]: InfoApi.listTemplates,
        [InfoApi.listUnitsOfMeasure.key]: InfoApi.listUnitsOfMeasure,
        [InfoApi.listVatTypes.key]: InfoApi.listVatTypes,
        [IssuedDocumentsApi.createIssuedDocument.key]: IssuedDocumentsApi.createIssuedDocument,
        [IssuedDocumentsApi.deleteIssuedDocument.key]: IssuedDocumentsApi.deleteIssuedDocument,
        [IssuedDocumentsApi.deleteIssuedDocumentAttachment.key]: IssuedDocumentsApi.deleteIssuedDocumentAttachment,
        [IssuedDocumentsApi.getEmailData.key]: IssuedDocumentsApi.getEmailData,
        [IssuedDocumentsApi.getExistingIssuedDocumentTotals.key]: IssuedDocumentsApi.getExistingIssuedDocumentTotals,
        [IssuedDocumentsApi.getIssuedDocument.key]: IssuedDocumentsApi.getIssuedDocument,
        [IssuedDocumentsApi.getIssuedDocumentPreCreateInfo.key]: IssuedDocumentsApi.getIssuedDocumentPreCreateInfo,
        [IssuedDocumentsApi.getNewIssuedDocumentTotals.key]: IssuedDocumentsApi.getNewIssuedDocumentTotals,
        [IssuedDocumentsApi.joinIssuedDocuments.key]: IssuedDocumentsApi.joinIssuedDocuments,
        [IssuedDocumentsApi.listIssuedDocuments.key]: IssuedDocumentsApi.listIssuedDocuments,
        [IssuedDocumentsApi.modifyIssuedDocument.key]: IssuedDocumentsApi.modifyIssuedDocument,
        [IssuedDocumentsApi.scheduleEmail.key]: IssuedDocumentsApi.scheduleEmail,
        [IssuedDocumentsApi.transformIssuedDocument.key]: IssuedDocumentsApi.transformIssuedDocument,
        [IssuedDocumentsApi.uploadIssuedDocumentAttachment.key]: IssuedDocumentsApi.uploadIssuedDocumentAttachment,
        [IssuedEInvoicesApi.getEInvoiceRejectionReason.key]: IssuedEInvoicesApi.getEInvoiceRejectionReason,
        [IssuedEInvoicesApi.getEInvoiceXml.key]: IssuedEInvoicesApi.getEInvoiceXml,
        [IssuedEInvoicesApi.sendEInvoice.key]: IssuedEInvoicesApi.sendEInvoice,
        [IssuedEInvoicesApi.verifyEInvoiceXml.key]: IssuedEInvoicesApi.verifyEInvoiceXml,
        [ProductsApi.createProduct.key]: ProductsApi.createProduct,
        [ProductsApi.deleteProduct.key]: ProductsApi.deleteProduct,
        [ProductsApi.getProduct.key]: ProductsApi.getProduct,
        [ProductsApi.listProducts.key]: ProductsApi.listProducts,
        [ProductsApi.modifyProduct.key]: ProductsApi.modifyProduct,
        [ReceiptsApi.createReceipt.key]: ReceiptsApi.createReceipt,
        [ReceiptsApi.deleteReceipt.key]: ReceiptsApi.deleteReceipt,
        [ReceiptsApi.getReceipt.key]: ReceiptsApi.getReceipt,
        [ReceiptsApi.getReceiptPreCreateInfo.key]: ReceiptsApi.getReceiptPreCreateInfo,
        [ReceiptsApi.getReceiptsMonthlyTotals.key]: ReceiptsApi.getReceiptsMonthlyTotals,
        [ReceiptsApi.listReceipts.key]: ReceiptsApi.listReceipts,
        [ReceiptsApi.modifyReceipt.key]: ReceiptsApi.modifyReceipt,
        [ReceivedDocumentsApi.createReceivedDocument.key]: ReceivedDocumentsApi.createReceivedDocument,
        [ReceivedDocumentsApi.deleteReceivedDocument.key]: ReceivedDocumentsApi.deleteReceivedDocument,
        [ReceivedDocumentsApi.deleteReceivedDocumentAttachment.key]: ReceivedDocumentsApi.deleteReceivedDocumentAttachment,
        [ReceivedDocumentsApi.getExistingReceivedDocumentTotals.key]: ReceivedDocumentsApi.getExistingReceivedDocumentTotals,
        [ReceivedDocumentsApi.getNewReceivedDocumentTotals.key]: ReceivedDocumentsApi.getNewReceivedDocumentTotals,
        [ReceivedDocumentsApi.getReceivedDocument.key]: ReceivedDocumentsApi.getReceivedDocument,
        [ReceivedDocumentsApi.getReceivedDocumentPreCreateInfo.key]: ReceivedDocumentsApi.getReceivedDocumentPreCreateInfo,
        [ReceivedDocumentsApi.listReceivedDocuments.key]: ReceivedDocumentsApi.listReceivedDocuments,
        [ReceivedDocumentsApi.modifyReceivedDocument.key]: ReceivedDocumentsApi.modifyReceivedDocument,
        [ReceivedDocumentsApi.uploadReceivedDocumentAttachment.key]: ReceivedDocumentsApi.uploadReceivedDocumentAttachment,
        [SettingsApi.createPaymentAccount.key]: SettingsApi.createPaymentAccount,
        [SettingsApi.createPaymentMethod.key]: SettingsApi.createPaymentMethod,
        [SettingsApi.createVatType.key]: SettingsApi.createVatType,
        [SettingsApi.deletePaymentAccount.key]: SettingsApi.deletePaymentAccount,
        [SettingsApi.deletePaymentMethod.key]: SettingsApi.deletePaymentMethod,
        [SettingsApi.deleteVatType.key]: SettingsApi.deleteVatType,
        [SettingsApi.getPaymentAccount.key]: SettingsApi.getPaymentAccount,
        [SettingsApi.getPaymentMethod.key]: SettingsApi.getPaymentMethod,
        [SettingsApi.getVatType.key]: SettingsApi.getVatType,
        [SettingsApi.modifyPaymentAccount.key]: SettingsApi.modifyPaymentAccount,
        [SettingsApi.modifyPaymentMethod.key]: SettingsApi.modifyPaymentMethod,
        [SettingsApi.modifyVatType.key]: SettingsApi.modifyVatType,
        [SuppliersApi.createSupplier.key]: SuppliersApi.createSupplier,
        [SuppliersApi.deleteSupplier.key]: SuppliersApi.deleteSupplier,
        [SuppliersApi.getSupplier.key]: SuppliersApi.getSupplier,
        [SuppliersApi.listSuppliers.key]: SuppliersApi.listSuppliers,
        [SuppliersApi.modifySupplier.key]: SuppliersApi.modifySupplier,
        [TaxesApi.createF24.key]: TaxesApi.createF24,
        [TaxesApi.deleteF24.key]: TaxesApi.deleteF24,
        [TaxesApi.deleteF24Attachment.key]: TaxesApi.deleteF24Attachment,
        [TaxesApi.getF24.key]: TaxesApi.getF24,
        [TaxesApi.listF24.key]: TaxesApi.listF24,
        [TaxesApi.modifyF24.key]: TaxesApi.modifyF24,
        [TaxesApi.uploadF24Attachment.key]: TaxesApi.uploadF24Attachment,
        [UserApi.getUserInfo.key]: UserApi.getUserInfo,
        [UserApi.listUserCompanies.key]: UserApi.listUserCompanies,
        [WebhooksApi.createWebhooksSubscription.key]: WebhooksApi.createWebhooksSubscription,
        [WebhooksApi.deleteWebhooksSubscription.key]: WebhooksApi.deleteWebhooksSubscription,
        [WebhooksApi.getWebhooksSubscription.key]: WebhooksApi.getWebhooksSubscription,
        [WebhooksApi.listWebhooksSubscriptions.key]: WebhooksApi.listWebhooksSubscriptions,
        [WebhooksApi.modifyWebhooksSubscription.key]: WebhooksApi.modifyWebhooksSubscription,
    },
};
